version: "3.7"
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    platform: linux/amd64
    networks:
      - selenoid-net
    volumes:
      - ./config:/etc/selenoid:ro
      - ./video:/opt/selenoid/video
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "5"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    platform: linux/amd64
    networks:
      - selenoid-net
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

networks:
  selenoid-net:
    driver: bridge